const CREATE_BOOKING_PENDING = 'CREATE_BOOKING_PENDING';
const CREATE_BOOKING_FULFILLED = 'CREATE_BOOKING_FULFILLED';
const CREATE_BOOKING_REJECTED = 'CREATE_BOOKING_REJECTED';
const FETCH_BOOKINGS_PENDING = 'FETCH_MOVIES_PENDING';
const FETCH_BOOKINGS_FULFILLED = 'FETCH_MOVIES_FULFILLED';
const FETCH_BOOKINGS_REJECTED = 'FETCH_MOVIES_REJECTED';

export {
    CREATE_BOOKING_PENDING,
    CREATE_BOOKING_FULFILLED,
    CREATE_BOOKING_REJECTED,
    FETCH_BOOKINGS_PENDING,
    FETCH_BOOKINGS_FULFILLED,
    FETCH_BOOKINGS_REJECTED,
};