// Action types
const SET_MOVIES = 'SET_MOVIES';
const SELECT_MOVIE = 'SELECT_MOVIE';
const FETCH_MOVIES_PENDING = 'FETCH_MOVIES_PENDING';
const FETCH_MOVIES_FULFILLED = 'FETCH_MOVIES_FULFILLED';
const FETCH_MOVIES_REJECTED = 'FETCH_MOVIES_REJECTED';

export {
    SET_MOVIES,
    SELECT_MOVIE,
    FETCH_MOVIES_PENDING,
    FETCH_MOVIES_FULFILLED,
    FETCH_MOVIES_REJECTED,
};