// Action types
const SET_SCREEN = 'SET_SCREEN';
const FETCH_SCREEN_PENDING = 'FETCH_SCREEN_PENDING';
const FETCH_SCREEN_FULFILLED = 'FETCH_SCREEN_FULFILLED';
const FETCH_SCREEN_REJECTED = 'FETCH_SCREEN_REJECTED';
const RESET_SCREEN = 'RESET_SCREEN';

export {
    SET_SCREEN,
    FETCH_SCREEN_PENDING,
    FETCH_SCREEN_FULFILLED,
    FETCH_SCREEN_REJECTED,
    RESET_SCREEN
};