// Action types
const SET_SHOWTIMES = 'SET_SHOWTIMES';
const SELECT_SHOWTIME = 'SELECT_SHOWTIME';
const FETCH_SHOWTIMES_PENDING = 'FETCH_SHOWTIMES_PENDING';
const FETCH_SHOWTIMES_FULFILLED = 'FETCH_SHOWTIMES_FULFILLED';
const FETCH_SHOWTIMES_REJECTED = 'FETCH_SHOWTIMES_REJECTED';
const RESET_SHOWTIMES = 'RESET_SHOWTIMES';

export {
    SET_SHOWTIMES,
    SELECT_SHOWTIME,
    FETCH_SHOWTIMES_PENDING,
    FETCH_SHOWTIMES_FULFILLED,
    FETCH_SHOWTIMES_REJECTED,
    RESET_SHOWTIMES
};